import { jsPDF } from "jspdf";
import type { StatutsSASData } from "./questionnaire-configs/statuts-sas";
import type { StatutsSCIData } from "./questionnaire-configs/statuts-sci";
import type { CGVEcommerceData } from "./questionnaire-configs/cgv-ecommerce";
import type { NDAData } from "./questionnaire-configs/nda";
import { generateStatutsSAS } from "./templates/statuts-sas";
import { generateStatutsSCI } from "./templates/statuts-sci";
import { generateCGVEcommerce } from "./templates/cgv-ecommerce";
import { generateNDA } from "./templates/nda";

export type DocumentType = "statuts-sas" | "statuts-sci" | "cgv-ecommerce" | "nda";

export interface DocumentMeta {
  title: string;
  subtitle: string;
}

function getMeta(type: DocumentType, data: Record<string, unknown>): DocumentMeta {
  switch (type) {
    case "statuts-sas":
      return {
        title: (data.denomination as string) || "Société",
        subtitle: "Statuts de SAS",
      };
    case "statuts-sci":
      return {
        title: (data.denomination as string) || "SCI",
        subtitle: "Statuts de SCI",
      };
    case "cgv-ecommerce":
      return {
        title: (data.denomination as string) || "Boutique",
        subtitle: "Conditions Générales de Vente",
      };
    case "nda":
      return {
        title: (data.partie_a_nom as string) || "NDA",
        subtitle: "Accord de confidentialité",
      };
  }
}

function generateContent(type: DocumentType, data: Record<string, unknown>): string {
  switch (type) {
    case "statuts-sas":
      return generateStatutsSAS(data as unknown as StatutsSASData);
    case "statuts-sci":
      return generateStatutsSCI(data as unknown as StatutsSCIData);
    case "cgv-ecommerce":
      return generateCGVEcommerce(data as unknown as CGVEcommerceData);
    case "nda":
      return generateNDA(data as unknown as NDAData);
  }
}

const MARGIN_LEFT = 25;
const MARGIN_RIGHT = 25;
const MARGIN_TOP = 30;
const MARGIN_BOTTOM = 25;
const LINE_HEIGHT = 6;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;

/**
 * Sanitize text for jsPDF's WinANSI encoding.
 * jsPDF's default Helvetica handles most French accents (é, è, à, etc.)
 * but has issues with certain Unicode characters.
 */
function sanitizeForPDF(text: string): string {
  return text
    // Typographic quotes and guillemets: jsPDF handles « » but not « »  with thin spaces
    .replace(/\u00A0/g, " ") // Non-breaking space -> regular space
    .replace(/\u202F/g, " ") // Narrow no-break space -> regular space
    .replace(/\u2009/g, " ") // Thin space -> regular space
    // Dashes
    .replace(/[\u2013\u2014]/g, "-") // em/en dash -> hyphen
    // Ellipsis
    .replace(/\u2026/g, "...")
    // Smart quotes
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"');
}

export interface GeneratePDFOptions {
  /**
   * When true, overlay a diagonal "QuickLegal" watermark on every page.
   * Used for the free demo flow. Paid PDFs (generated by the webhook) are
   * produced without a watermark.
   */
  watermark?: boolean;
}

export function generatePDF(
  type: DocumentType,
  data: Record<string, unknown>,
  options: GeneratePDFOptions = {}
): Buffer {
  const withWatermark = options.watermark ?? true;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const meta = getMeta(type, data);
  const rawText = generateContent(type, data);
  const text = sanitizeForPDF(rawText);

  let y = MARGIN_TOP;
  let pageNum = 1;

  function addPageNumber() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${pageNum}`, PAGE_WIDTH / 2, 290, { align: "center" });
    doc.text(`${meta.title.toUpperCase()} - ${meta.subtitle}`, MARGIN_LEFT, 290);
  }

  function addWatermark() {
    if (!withWatermark) return;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(40);
    doc.setTextColor(240, 240, 240);
    doc.text("QuickLegal - DEMO", PAGE_WIDTH / 2, 150, {
      align: "center",
      angle: 45,
    });
  }

  function checkNewPage(neededSpace: number = LINE_HEIGHT * 2) {
    if (y + neededSpace > 297 - MARGIN_BOTTOM) {
      addPageNumber();
      addWatermark();
      doc.addPage();
      pageNum++;
      y = MARGIN_TOP;
    }
  }

  const lines = text.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();

    if (!trimmed) {
      y += LINE_HEIGHT * 0.5;
      checkNewPage();
      continue;
    }

    // TITLE LINES (all uppercase, long enough)
    if (
      trimmed === trimmed.toUpperCase() &&
      trimmed.length > 10 &&
      !trimmed.startsWith("-") &&
      !trimmed.startsWith("[")
    ) {
      checkNewPage(LINE_HEIGHT * 3);
      y += LINE_HEIGHT;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(20, 20, 60);

      const titleLines = doc.splitTextToSize(trimmed, CONTENT_WIDTH);
      for (const tl of titleLines) {
        checkNewPage();
        doc.text(tl, PAGE_WIDTH / 2, y, { align: "center" });
        y += LINE_HEIGHT * 1.3;
      }
      y += LINE_HEIGHT * 0.5;
      continue;
    }

    // ARTICLE HEADERS
    if (
      trimmed.startsWith("Article ") ||
      trimmed.startsWith("TITRE ") ||
      trimmed.startsWith("DÉSIGNATION") ||
      trimmed.startsWith("DESIGNATION") ||
      trimmed.startsWith("PRÉAMBULE") ||
      trimmed.startsWith("PREAMBULE")
    ) {
      checkNewPage(LINE_HEIGHT * 4);
      y += LINE_HEIGHT;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(30, 30, 80);

      const headerParts = trimmed.split(" - ");
      if (headerParts.length > 1) {
        doc.text(headerParts[0] + " -", MARGIN_LEFT, y);
        y += LINE_HEIGHT;
        doc.setFont("helvetica", "bolditalic");
        const subLines = doc.splitTextToSize(
          headerParts.slice(1).join(" - "),
          CONTENT_WIDTH
        );
        for (const sl of subLines) {
          checkNewPage();
          doc.text(sl, MARGIN_LEFT, y);
          y += LINE_HEIGHT;
        }
      } else {
        const headerLines = doc.splitTextToSize(trimmed, CONTENT_WIDTH);
        for (const hl of headerLines) {
          checkNewPage();
          doc.text(hl, MARGIN_LEFT, y);
          y += LINE_HEIGHT;
        }
      }
      y += LINE_HEIGHT * 0.3;
      continue;
    }

    // SIGNATURE HINT
    if (
      trimmed.startsWith("(signature précédée") ||
      trimmed.startsWith("(signature precedee")
    ) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(120, 120, 120);
      checkNewPage();
      doc.text(trimmed, MARGIN_LEFT, y);
      y += LINE_HEIGHT;
      y += LINE_HEIGHT * 2;
      doc.setDrawColor(180, 180, 180);
      doc.line(MARGIN_LEFT, y, MARGIN_LEFT + 60, y);
      y += LINE_HEIGHT * 2;
      continue;
    }

    // BULLET POINTS
    if (trimmed.startsWith("- ") || trimmed.match(/^\d+\.\s/)) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      const bulletLines = doc.splitTextToSize(trimmed, CONTENT_WIDTH - 5);
      for (let i = 0; i < bulletLines.length; i++) {
        checkNewPage();
        doc.text(bulletLines[i], MARGIN_LEFT + (i === 0 ? 0 : 5), y);
        y += LINE_HEIGHT;
      }
      continue;
    }

    // NOTES in brackets
    if (trimmed.startsWith("[NOTE")) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      const noteLines = doc.splitTextToSize(trimmed, CONTENT_WIDTH - 10);
      for (const nl of noteLines) {
        checkNewPage();
        doc.text(nl, MARGIN_LEFT + 5, y);
        y += LINE_HEIGHT * 0.9;
      }
      y += LINE_HEIGHT * 0.3;
      continue;
    }

    // Regular text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(40, 40, 40);

    const wrappedLines = doc.splitTextToSize(trimmed, CONTENT_WIDTH);
    for (const wl of wrappedLines) {
      checkNewPage();
      doc.text(wl, MARGIN_LEFT, y);
      y += LINE_HEIGHT;
    }
  }

  addPageNumber();
  addWatermark();

  const arrayBuffer = doc.output("arraybuffer");
  return Buffer.from(arrayBuffer);
}

// Legacy export for backwards compatibility
export function generateStatutsPDF(data: StatutsSASData): Buffer {
  return generatePDF("statuts-sas", data as unknown as Record<string, unknown>);
}
